# Generated by Django 3.1.7 on 2021-03-29 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210329_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conclusion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
